apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/metallb/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
