apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: wordpress
type: Opaque
stringData:
  mariadb-password: 3fzxIS7zU4K1gYob
  mariadb-user: wpuser
  mariadb-database: bitnami_wordpress