apiVersion: v1
kind: Secret
metadata:
  name: sops-age-key
  namespace: flux-system
type: Opaque
stringData:
  age.agekey: |
    AGE-SECRET-KEY-1LN7RAE5005K4UTFYX6ZN7958SQ6VVM9XG7AK5QKXNG2K0N8CHFPQ9E87KK
